#!/usr/bin/env python3
# sandbox_executor.py
import ast
import shutil
import subprocess
import tempfile
import os
import json
import sys
import time
from pathlib import Path
from typing import Optional, Dict, Any

from app_config import get_config

class SandboxedExecutor:
    """
    Executes code generated by the Strategic Planner in a secure, isolated environment.

    Features:
    - AST-validated: code is parsed and checked against an explicit
      import whitelist and a call/attribute blocklist *before* it is
      ever written to disk or executed - not just scanned for a
      handful of substrings.
    - Writes code to a temporary file.
    - Runs code in a restricted subprocess with a scrubbed environment,
      an enforced memory ceiling, and an enforced CPU time ceiling.
    - When `firejail` is installed on the host, runs the subprocess
      inside it for real OS-level isolation (separate namespace,
      no-new-privs, network disabled) - AST validation is defense in
      depth, but it's still trusting the same Python interpreter as
      the boundary. firejail is optional and detected automatically;
      everything still works (just with a smaller isolation boundary)
      when it isn't present, which is the common case on Termux/Android.
    - Captures stdout/stderr and exit codes.
    - Enforces timeouts to prevent infinite loops.
    """

    # Previously this was defined but never actually consulted -
    # _validate_imports() only ever checked a 7-word substring
    # blocklist that didn't even mention 'os' (which was, bizarrely,
    # in this very allowlist), so os.system(...)/os.popen(...) and
    # any module outside those 7 words sailed straight through
    # undetected. This set is now the actual, enforced source of truth.
    ALLOWED_IMPORTS = {'json', 'sys', 're', 'datetime', 'math', 'random',
                       'string', 'itertools', 'collections', 'statistics'}

    # Calls that must never appear, regardless of what's imported -
    # covers the standard sandbox-escape toolbox (dynamic import,
    # arbitrary eval/exec, introspection into living objects to reach
    # __subclasses__ etc.).
    FORBIDDEN_CALL_NAMES = {
        'eval', 'exec', 'compile', 'open', 'input', '__import__',
        'globals', 'locals', 'vars', 'getattr', 'setattr', 'delattr',
    }

    def __init__(self, timeout_seconds: Optional[int] = None,
                 max_memory_mb: Optional[int] = None,
                 max_cpu_seconds: Optional[int] = None):
        cfg = get_config().get("sandbox", {})
        # Explicit constructor args still win over config, config wins
        # over the hardcoded fallback - previously these were only ever
        # hardcoded constructor defaults with no config-driven override.
        self.timeout = timeout_seconds if timeout_seconds is not None else cfg.get("timeout_seconds", 30)
        self.max_memory = max_memory_mb if max_memory_mb is not None else cfg.get("max_memory_mb", 256)
        self.max_cpu_seconds = max_cpu_seconds if max_cpu_seconds is not None else cfg.get("max_cpu_seconds", 10)
        self._use_firejail = cfg.get("use_firejail_if_available", True) and shutil.which("firejail") is not None

    def _validate_imports(self, code: str) -> bool:
        """
        AST-based validation: parse the code and reject anything that
        imports outside ALLOWED_IMPORTS, calls a forbidden name, or
        touches a dunder attribute (the standard route to
        ().__class__.__bases__[0].__subclasses__()-style sandbox
        escapes). Returns False (rejected) on any parse error too -
        fail closed, not open.

        This replaces the previous implementation, which only checked
        for the literal substrings "import subprocess", "import
        shutil", "import socket", "import urllib", "import requests",
        "eval(", and "exec(" - and never referenced self.allowed_imports
        at all. `os` was explicitly permitted (`os.system(...)` was
        therefore always available), and anything not named in that
        7-item list - ftplib, ctypes, multiprocessing, importlib,
        pty, etc. - was never checked either.
        """
        try:
            tree = ast.parse(code)
        except SyntaxError:
            return False

        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name.split('.')[0] not in self.ALLOWED_IMPORTS:
                        return False
            elif isinstance(node, ast.ImportFrom):
                root = (node.module or '').split('.')[0]
                if root not in self.ALLOWED_IMPORTS:
                    return False
            elif isinstance(node, ast.Name):
                if node.id in self.FORBIDDEN_CALL_NAMES:
                    return False
                if node.id.startswith('__') and node.id.endswith('__'):
                    return False
            elif isinstance(node, ast.Attribute):
                if node.attr.startswith('__') and node.attr.endswith('__'):
                    return False
        return True

    def execute(self, code: str, working_dir: Optional[str] = None) -> Dict[str, Any]:
        """
        Executes the provided Python code string.

        Args:
            code: The Python code string generated by the Planner.
            working_dir: Optional directory to run the code in (defaults to temp dir).

        Returns:
            Dictionary with 'success', 'output', 'error', and 'exit_code'.
        """
        # 1. Pre-flight Safety Check
        if not self._validate_imports(code):
            return {
                "success": False,
                "output": "",
                "error": "SECURITY BLOCK: Code contains forbidden imports (e.g., subprocess, socket).",
                "exit_code": -1
            }
        # 2. Prepare Temporary File
        with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as tmp_file:
            tmp_file.write(code)
            tmp_path = tmp_file.name
        try:
            # 3. Define Execution Command
            cmd = [sys.executable, tmp_path]
            if self._use_firejail:
                # Real OS-level isolation when available: separate
                # namespace, no new privileges, network disabled,
                # private /tmp. AST validation above is defense in
                # depth; this is an actual second, independent boundary
                # that doesn't rely on the validator having caught
                # everything. Falls back silently to subprocess-only
                # isolation (still with the resource limits below) on
                # systems without firejail - most Termux/Android hosts.
                cmd = [
                    "firejail", "--quiet", "--noprofile",
                    "--net=none", "--private-tmp", "--nonewprivs",
                    "--seccomp",
                ] + cmd

            # ── Hardened env isolation ─────────────────────────────────────
            # Build a minimal environment: only what Python needs to run.
            # Strip API keys, home dir, SSH paths, and anything sensitive
            # so sandboxed code cannot read credentials from the environment.
            _ALLOWED_ENV_KEYS = {
                "PATH",           # needed to find python3 / system tools
                "PYTHONPATH",     # needed for imports
                "PYTHONHOME",     # needed on some systems
                "LANG",           # locale (safe)
                "LC_ALL",         # locale (safe)
                "TMPDIR",         # temp dir for the subprocess
                "TMP",
                "TEMP",
                "SYSTEMROOT",     # Windows compatibility
                "COMSPEC",        # Windows compatibility
            }
            env = {k: v for k, v in os.environ.items() if k in _ALLOWED_ENV_KEYS}
            # Explicitly scrub any credentials that might have slipped through
            for _secret_key in ("GROQ_API_KEY", "OPENAI_API_KEY", "HOME", "USER",
                                 "LOGNAME", "SHELL", "SSH_AUTH_SOCK",
                                 "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"):
                env.pop(_secret_key, None)
            # ─────────────────────────────────────────────────────────────

            # 4. Execute in Subprocess with Timeout and Memory Limit
            start_time = time.time()

            def _apply_resource_limits():
                """
                preexec_fn: runs in the child after fork(), before exec.
                Actually enforces max_memory_mb (previously configured
                in __init__ but never applied anywhere - the RLIMIT
                call was left as a TODO comment). Also puts the child
                in its own process group so a runaway subprocess it
                spawns can be killed alongside it on timeout.
                """
                try:
                    import resource
                    mem_bytes = self.max_memory * 1024 * 1024
                    resource.setrlimit(resource.RLIMIT_AS, (mem_bytes, mem_bytes))
                    resource.setrlimit(resource.RLIMIT_CPU, (self.max_cpu_seconds, self.max_cpu_seconds))
                except Exception:
                    pass  # not available on this platform (e.g. some Android/Termux builds) - degrade gracefully
                try:
                    os.setsid()
                except Exception:
                    pass

            try:
                result = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    timeout=self.timeout,
                    cwd=working_dir,
                    env=env,
                    preexec_fn=_apply_resource_limits if hasattr(os, "setsid") else None,
                )
                elapsed = time.time() - start_time
                return {
                    "success": result.returncode == 0,
                    "output": result.stdout.strip(),
                    "error": result.stderr.strip(),
                    "exit_code": result.returncode,
                    "execution_time_ms": int(elapsed * 1000)
                }
            except subprocess.TimeoutExpired:
                return {
                    "success": False,
                    "output": "",
                    "error": f"TIMEOUT: Code execution exceeded {self.timeout} seconds. Possible infinite loop.",
                    "exit_code": -2
                }
            except Exception as e:
                return {
                    "success": False,
                    "output": "",
                    "error": f"EXECUTION ERROR: {str(e)}",
                    "exit_code": -3
                }
        finally:
            # 5. Cleanup
            if os.path.exists(tmp_path):
                os.remove(tmp_path)

# ─── Example Usage Simulation ───
if __name__ == "__main__":
    executor = SandboxedExecutor(timeout_seconds=10)
    # Scenario 1: Safe Code (Reading a file)
    safe_code = """
import json
import os

# Simulate reading a config
config_data = {"version": "1.2.0", "author": "Partnership_AI"}
print(json.dumps(config_data))
"""
    print("─── Running Safe Code ───")
    res = executor.execute(safe_code)
    print(f"Success: {res['success']}")
    print(f"Output: {res['output']}")
    if res['error']: print(f"Error: {res['error']}")
    # Scenario 2: Unsafe Code (Blocked)
    unsafe_code = """
import subprocess
subprocess.run(['ls', '-la'])
"""
    print("\n─── Running Unsafe Code (Should Block) ───")
    res = executor.execute(unsafe_code)
    print(f"Success: {res['success']}")
    print(f"Error: {res['error']}")
    # Scenario 3: Infinite Loop (Timeout)
    loop_code = """
while True:
    pass
"""
    print("\n─── Running Infinite Loop (Should Timeout) ───")
    res = executor.execute(loop_code)
    print(f"Success: {res['success']}")
    print(f"Error: {res['error']}")
