"""
conversation_engine/plugin_loader.py
Plugin auto-discovery and registration for Partnership_AI.

Partnership_AI's plugin system lets you extend the agent's capabilities by
dropping a Python file into the ``plugins/`` directory. Each plugin file uses
the standard ``@register_action`` decorator — the loader simply discovers
and imports them automatically, with no changes to any core file.

How it works:
  1. On startup (or when called explicitly), ``load_all_plugins()`` scans
     the ``plugins/`` directory for ``*.py`` files.
  2. Each file is imported as a module. The ``@register_action`` decorators
     inside the file fire at import time, registering actions into the
     central ACTIONS/ACTION_METADATA/ACTION_SCHEMAS dicts.
  3. The loader logs which plugins loaded successfully and which failed.

Plugin file format:
  A plugin is just a regular Python file with one or more functions decorated
  with ``@register_action("action_name", input_schema={...})``. Example::

      from conversation_engine.action_registry import register_action, ActionResult

      @register_action("my_custom_action", input_schema={
          "type": "object",
          "required": ["text"],
          "properties": {"text": {"type": "string"}},
      })
      def my_action(text: str) -> ActionResult:
          return ActionResult(success=True, data={"echo": text})

The evolution pipeline can also generate new plugins by writing a .py file
into ``plugins/`` and calling ``load_all_plugins()`` to register it.

Directory structure:
    Partnership_AI/
      plugins/
        example_plugin.py    ← any .py file here is auto-loaded
        another_plugin.py
"""
from __future__ import annotations
from typing import Dict, List, Tuple
from pathlib import Path
import importlib
import importlib.util
import logging
import sys

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────

_PLUGINS_DIR = Path(__file__).resolve().parent.parent / "plugins"

# Track which plugins have been loaded (for idempotency and reporting)
_loaded_plugins: Dict[str, bool] = {}  # plugin_name -> loaded_successfully


def get_plugins_dir() -> Path:
    """
    Return the plugins directory, creating it if it doesn't exist.

    Returns:
        Path to the plugins directory (guaranteed to exist).
    """
    _PLUGINS_DIR.mkdir(parents=True, exist_ok=True)
    # Ensure there's an __init__.py so Python treats it as a package
    init_file = _PLUGINS_DIR / "__init__.py"
    if not init_file.exists():
        init_file.write_text('"""Auto-generated by plugin_loader.py"""\n')
    return _PLUGINS_DIR


def load_all_plugins() -> Tuple[List[str], List[Tuple[str, str]]]:
    """
    Discover and import all plugin files in the plugins/ directory.

    Each ``*.py`` file (except ``__init__.py``) is imported as a module.
    The ``@register_action`` decorators inside each file fire at import time,
    registering actions into the central registry.

    This function is idempotent — calling it multiple times will not re-import
    already-loaded plugins (Python's ``sys.modules`` cache handles this).

    Returns:
        Tuple of (loaded_names, failed_list) where:
        - loaded_names: list of plugin module names that loaded successfully
        - failed_list: list of (plugin_name, error_message) tuples for failures
    """
    plugins_dir = get_plugins_dir()
    loaded: List[str] = []
    failed: List[Tuple[str, str]] = []

    plugin_files = sorted(plugins_dir.glob("*.py"))
    plugin_files = [f for f in plugin_files if f.name != "__init__.py"]

    if not plugin_files:
        logger.info("[Plugins] No plugin files found in %s", plugins_dir)
        return loaded, failed

    logger.info("[Plugins] Discovering %d plugin file(s) in %s", len(plugin_files), plugins_dir)

    for plugin_file in plugin_files:
        plugin_name = plugin_file.stem  # filename without .py

        # Skip if already loaded
        if plugin_name in _loaded_plugins and _loaded_plugins[plugin_name]:
            logger.debug("[Plugins] %s already loaded, skipping.", plugin_name)
            continue

        try:
            # Import using importlib for clean module naming
            module_name = f"plugins.{plugin_name}"

            # If already in sys.modules (from a prior call), skip
            if module_name in sys.modules:
                _loaded_plugins[plugin_name] = True
                loaded.append(plugin_name)
                continue

            spec = importlib.util.spec_from_file_location(module_name, plugin_file)
            if spec is None or spec.loader is None:
                raise ImportError(f"Could not create module spec for {plugin_file}")

            module = importlib.util.module_from_spec(spec)
            sys.modules[module_name] = module
            spec.loader.exec_module(module)

            _loaded_plugins[plugin_name] = True
            loaded.append(plugin_name)
            logger.info("[Plugins] ✅ Loaded plugin: %s", plugin_name)

        except Exception as e:
            _loaded_plugins[plugin_name] = False
            failed.append((plugin_name, str(e)))
            logger.error("[Plugins] ❌ Failed to load plugin %s: %s", plugin_name, e)

    if loaded:
        logger.info("[Plugins] Loaded %d plugin(s): %s", len(loaded), ", ".join(loaded))
    if failed:
        logger.warning(
            "[Plugins] Failed to load %d plugin(s): %s",
            len(failed),
            ", ".join(name for name, _ in failed),
        )

    return loaded, failed


def get_plugin_status() -> List[Dict]:
    """
    Return a status report for all discovered plugins.

    Returns:
        List of dicts with keys: name, loaded, file, error (if any).
    """
    plugins_dir = get_plugins_dir()
    plugin_files = [f for f in sorted(plugins_dir.glob("*.py")) if f.name != "__init__.py"]

    return [
        {
            "name": f.stem,
            "loaded": _loaded_plugins.get(f.stem, False),
            "file": str(f),
            "error": None if _loaded_plugins.get(f.stem, False) else "Not loaded",
        }
        for f in plugin_files
    ]


def reload_plugin(plugin_name: str) -> bool:
    """
    Force-reload a single plugin by name.

    Removes the plugin from sys.modules and re-imports it. Useful for
    development and for the evolution pipeline after writing a new plugin.

    Args:
        plugin_name: The plugin's filename stem (without .py extension).

    Returns:
        True if the plugin reloaded successfully, False otherwise.
    """
    plugin_file = get_plugins_dir() / f"{plugin_name}.py"
    if not plugin_file.exists():
        logger.warning("[Plugins] Plugin file not found: %s", plugin_file)
        return False

    module_name = f"plugins.{plugin_name}"

    # Remove from sys.modules to force a fresh import
    if module_name in sys.modules:
        del sys.modules[module_name]
    _loaded_plugins.pop(plugin_name, None)

    try:
        spec = importlib.util.spec_from_file_location(module_name, plugin_file)
        if spec is None or spec.loader is None:
            raise ImportError(f"Could not create module spec for {plugin_file}")

        module = importlib.util.module_from_spec(spec)
        sys.modules[module_name] = module
        spec.loader.exec_module(module)

        _loaded_plugins[plugin_name] = True
        logger.info("[Plugins] ✅ Reloaded plugin: %s", plugin_name)
        return True

    except Exception as e:
        _loaded_plugins[plugin_name] = False
        logger.error("[Plugins] ❌ Failed to reload plugin %s: %s", plugin_name, e)
        return False
